### ISSUE TITLE
Стоит ли явно указать путь до логотипа?

### ISSUE THREAD

**Issue by batkor** [Niklan/Glisseo#11]
В `STARTER.info.yml` возможно стоит указать явный путь до логотипа?

```yaml
# Theme base information.
screenshot: screenshot.png
logo: logo.svg
name: Glisseo (starter theme)
type: theme
base theme: glisseo
```
