### ISSUE TITLE
Возможно стоит отключить системные библиотеки?

### ISSUE THREAD

**Issue by batkor** [Niklan/Glisseo#8]
Добавить в `themes/contrib/glisseo/STARTER/STARTER.layouts.yml`
```
...
libraries-override:
  system/base: false

```
и добавить дефолтный стиль для селектора в файл `/themes/contrib/glisseo/STARTER/assets/scss/generic/_normalize.scss` 
```
.visually-hidden{
  display: none;
}
```

**Comment by iryston** [comment]
Не стоит добавлять хелпер в `Glisseo/STARTER/assets/scss/generic/_normalize.scss`.
Для этого есть `Glisseo/STARTER/assets/scss/tools/mixins/_helpers.scss`.
И `.visually-hidden` это точно не `display: none;`.
Хороший пример, как прятать элементы есть в [html5-boilerplate](https://github.com/h5bp/html5-boilerplate)

```css
/*
 * Hide visually and from screen readers
 */

 .hidden {
  display: none !important;
}

/*
* Hide only visually, but have it available for screen readers:
* https://snook.ca/archives/html_and_css/hiding-content-for-accessibility
*
* 1. For long content, line feeds are not interpreted as spaces and small width
*    causes content to wrap 1 word per line:
*    https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe
*/

.visuallyhidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
  white-space: nowrap; /* 1 */
}

/*
* Extends the .visuallyhidden class to allow the element
* to be focusable when navigated to via the keyboard:
* https://www.drupal.org/node/897638
*/

.visuallyhidden.focusable:active,
.visuallyhidden.focusable:focus {
  clip: auto;
  height: auto;
  margin: 0;
  overflow: visible;
  position: static;
  width: auto;
  white-space: inherit;
}

/*
* Hide visually and from screen readers, but maintain layout
*/

.invisible {
  visibility: hidden;
}
```

**Comment by batkor** [comment]
Да кому как удобно и угодно, можно из актуального Drupal8.6.10/theme/stable
```
/**
 * @file
 * Utility classes to hide elements in different ways.
 */

/**
 * Hide elements from all users.
 *
 * Used for elements which should not be immediately displayed to any user. An
 * example would be collapsible details that will be expanded with a click
 * from a user. The effect of this class can be toggled with the jQuery show()
 * and hide() functions.
 */
.hidden {
  display: none;
}

/**
 * Hide elements visually, but keep them available for screen readers.
 *
 * Used for information required for screen reader users to understand and use
 * the site where visual display is undesirable. Information provided in this
 * manner should be kept concise, to avoid unnecessary burden on the user.
 * "!important" is used to prevent unintentional overrides.
 */
.visually-hidden {
  position: absolute !important;
  clip: rect(1px, 1px, 1px, 1px);
  overflow: hidden;
  height: 1px;
  width: 1px;
  word-wrap: normal;
}

/**
 * The .focusable class extends the .visually-hidden class to allow
 * the element to be focusable when navigated to via the keyboard.
 */
.visually-hidden.focusable:active,
.visually-hidden.focusable:focus {
  position: static !important;
  clip: auto;
  overflow: visible;
  height: auto;
  width: auto;
}

/**
 * Hide visually and from screen readers, but maintain layout.
 */
.invisible {
  visibility: hidden;
}

```
Но это не имеет никакого значения, главная задача это то что надо скрыть дефолтный селектор 
`visually-hidden`который используется в контрибных модулях adminToolbar, Contextual Links и т.д.

**Comment by batkor** [comment]
Или вот так в `Glisseo/STARTER/assets/scss/generic/_normalize.scss`
```
.visually-hidden{
  @include hide-element;
}
```
и как предложил в [комменте](https://github.com/Niklan/Glisseo/issues/8#issuecomment-468411646) `Glisseo/STARTER/assets/scss/tools/mixins/_helpers.scss`. добавить
```
// =====================================
// Hide element.
//
// Hide elements visually, but keep them available for screen readers.
//
// Used for information required for screen reader users to understand and use
// the site where visual display is undesirable. Information provided in this
// manner should be kept concise, to avoid unnecessary burden on the user.
// "!important" is used to prevent unintentional overrides.
//
// =====================================
@mixin hide-element {
  position: absolute !important;
  clip: rect(1px, 1px, 1px, 1px);
  overflow: hidden;
  height: 1px;
  width: 1px;
  word-wrap: normal;
  /**
   * The .focusable class extends the .visually-hidden class to allow
   * the element to be focusable when navigated to via the keyboard.
   */
  &.focusable {
    &:active, &:focus{
      position: static !important;
      clip: auto;
      overflow: visible;
      height: auto;
      width: auto;
    }
  }
}
```

**Comment by Niklan** [comment]
Думаю нам стоит сделать миксин по типу [этого](https://github.com/inuitcss/inuitcss/blob/develop/tools/_tools.hidden.scss)

```scss
@mixin inuit-hidden-visually() {
  border: 0 !important;
  clip: rect(0 0 0 0) !important;
  clip-path: inset(50%) !important;
  height: 1px !important;
  margin: -1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  white-space: nowrap !important;
  width: 1px !important;
}
```
Только без импортантов на каждой строке, дико как-то.

Но классы, где и будет вызываться миксин, скорее всего, надо выносить в в utilities, так как это самый высокий уровень в ITCSS, для чего он какраз и создан, выходит что эти классы в utilities перетрут любые другие что были до него на элементе и никакие important не понадобатся.

Вообще, возможно тогда стоит разобраться какие ещё системные либы не нужны и срезать их, но дефолтные классы друпала, какраз, типа `.visually-hidden` надо будет определить, как это сделано для форм, хотябы в минимальном виде для заточки под себя и чтобы работало ожидаемо, в данном случае, скрывался элемент, которые по мнению бэкенда должен быть скрыт.
